apiVersion: v1
data:
  config.json: |- 
    {
      "sink": "http",
      "httpSinkUrl": "http://localhost:8080",
      "httpSinkBufferSize": 1500,
      "httpSinkDiscardMessages": true
    }
kind: ConfigMap
metadata:
  name: litmus-eventrouter-http-cm
  namespace: litmus
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: litmus-eventrouter
  namespace: litmus
  labels:
    app: litmus-eventrouter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: litmus-eventrouter
  template:
    metadata:
      labels:
        app: litmus-eventrouter
    spec:
      containers:
        - name: litmus-eventrouter
          image: gcr.io/heptio-images/eventrouter:latest
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - name: config-volume
            mountPath: /etc/eventrouter
      serviceAccount: litmus
      volumes:
        - name: config-volume
          configMap:
            name: litmus-eventrouter-http-cm
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: litmus-eventrouter
  name: litmus-eventrouter
  namespace: litmus
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: litmus-eventrouter
  type: NodePort
