#When Grafana starts, it will update/insert this datasource.
apiVersion: v1
kind: ConfigMap
metadata:
  name: litmus-events-grafana-datasource-provision
data:
  prometheus-datasource.yaml: |
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      access: direct
      orgId: 1
      url: http://localhost:9090
      isDefault: false
      version: 1
      editable: true