apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels: 
    app: nginx
  annotations:
    litmuschaos.io/chaos: "true"
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
---
kind: Service 
apiVersion: v1 
metadata:
  name: nginx
spec:
  type: ClusterIP
  selector:
    app: nginx 
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
