apiVersion: v1
data:
  metricbeat.yml: |-
    metricbeat.config.modules:
      # Mounted `metricbeat-daemonset-modules` configmap:
      path: ${path.config}/modules.d/*.yml
      # Reload module configs as they change:
      reload.enabled: false

    processors:
      - add_cloud_metadata:

    cloud.id: ${ELASTIC_CLOUD_ID}
    cloud.auth: ${ELASTIC_CLOUD_AUTH}

    output.elasticsearch:
      hosts: ['${ELASTICSEARCH_HOST:elasticsearch}:${ELASTICSEARCH_PORT:9200}']
      username: ${ELASTICSEARCH_USERNAME}
      password: ${ELASTICSEARCH_PASSWORD}
kind: ConfigMap
metadata:
  labels:
    k8s-app: metricbeat
  name: metricbeat-deployment-config
  namespace: litmus
---
apiVersion: v1
data:
  kubernetes.yml: |-
    - module: kubernetes
      metricsets:
        - event
      period: 10s
      host: k8s-events
kind: ConfigMap
metadata:
  labels:
    k8s-app: metricbeat
  name: metricbeat-deployment-modules
  namespace: litmus
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    k8s-app: metricbeat
  name: metricbeat
  namespace: litmus
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: metricbeat
  template:
    metadata:
      labels:
        k8s-app: metricbeat
    spec:
      containers:
      - args:
        - -c
        - /etc/metricbeat.yml
        - -e
        env:
        - name: ELASTICSEARCH_HOST
          value: elasticsearch-master.default.svc.cluster.local
        - name: ELASTICSEARCH_PORT
          value: "9200"
        - name: ELASTICSEARCH_USERNAME
          value: elastic
        - name: ELASTICSEARCH_PASSWORD
          value: changeme
        - name: ELASTIC_CLOUD_ID
        - name: ELASTIC_CLOUD_AUTH
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        image: docker.elastic.co/beats/metricbeat:7.6.2
        imagePullPolicy: IfNotPresent
        name: metricbeat
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
        securityContext:
          runAsUser: 0
        volumeMounts:
        - mountPath: /etc/metricbeat.yml
          name: config
          readOnly: true
          subPath: metricbeat.yml
        - mountPath: /usr/share/metricbeat/modules.d
          name: modules
          readOnly: true
      hostNetwork: true
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccount: litmus
      serviceAccountName: litmus
      volumes:
      - configMap:
          defaultMode: 384
          name: metricbeat-deployment-config
        name: config
      - configMap:
          defaultMode: 384
          name: metricbeat-deployment-modules
        name: modules