{
 "title": "Litmus chaos exporter metrics",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DataSource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Total Experiments",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "cluster_overall_experiments_count"
    }
   ]
  },
  {
   "title": "Total Failed Experiments",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 0 },
   "targets": [
    {
     "expr": "cluster_overall_failed_experiments"
    }
   ]
  },
  {
   "title": "Total Passed Experiments",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 10, "y": 0 },
   "targets": [
    {
     "expr": "cluster_overall_passed_experiments"
    }
   ]
  }
 ]
}